#Step1: import libraries
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.tools.retriever import create_retriever_tool
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage
from settings import GEMINI_API_KEY, GEMINI_MODEL


#Step2: Initialize gemini llm
llm = ChatGoogleGenerativeAI(
    model=GEMINI_MODEL,
    api_key=GEMINI_API_KEY,
    temperature=0.3
)

#step3: Create FAISS Vector Store with 3 financial facts
financial_facts = [
    "EBITDA stands for Earnings Before Interest, Taxes, Depreciation and Amortization. It measures core operational profitability.",
    "Revenue is the total income generated by a company from its business activities before any expenses are deducted.",
    "Net profit is the amount remaining after all expenses, taxes, and costs have been deducted from total revenue."
]

embeddings_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2") # A lightweight model for generating embeddings, suitable for small datasets and quick retrieval.

vector_store = FAISS.from_texts(financial_facts, embeddings_model) # create FAISS vector store fom financial_facts

retriever = vector_store.as_retriever(search_kwargs={"k":1}) # k=1 means the retriever will return the top 1 most relevant fact from the vector store

#Step4: Create a retriever tool that the LLM can call to access financial facts when needed, will be invoked by the llm
retriever_tool = create_retriever_tool(
    retriever=retriever,
    name="financial_facts_retriever",
    description="Use this tool to retrieve financial facts related to EBITDA, Revenue, and Net Profit."
)


# Figured out that ConversationBufferMemory is deprecated in my langChainversion
# So I switched to InMemoryChatMessageHistory and created a custom memory tool
# because we need the FULL conversation history preserved exactly.
# Why not WindowMemory? It only keeps the last N turns —> we'd lose Turn 1 context by Turn 3.
# Why not SummaryMemory? It compresses history into a summary —> fine for long chats
# but loses exact details like specific numbers ("$10M"), which matters in finance.
# BufferMemory (and similar tools) keeps everything verbatim —> perfect for a short financial conversation.

memory = InMemoryChatMessageHistory() #step5: initialize memory to store full conversation


#step6: build prompt teplate [with sys instructions, conversation history placeholder, and user input]
prompt = ChatPromptTemplate.from_messages([
    ("system", """
        You are a helpful financial assistant (FinAgent).
        You have access to a financial knowledge base tool for looking up definitions.
        Use the tool when asked about financial terms or definitions.
        Use your conversation memory to recall anything the user told you earlier.
"""),
    MessagesPlaceholder (variable_name="history"),
    ("human", "{input}")
])

#step7: build LCEL chain: prompt -> llm (with tool access) -> response
chain = prompt | llm.bind_tools([retriever_tool])


#step8: create a function to handle the flow: get user input-> call chain->check for tool calls->  update memory -> return response
def chat(user_input: str) -> str:
    history = memory.messages

    response = chain.invoke({
        "input": user_input,
        "history": history
    })

    # Extract text cleanly from Gemini's response
    if isinstance(response.content, list):
        result = next(
            block["text"] for block in response.content 
            if isinstance(block, dict) and block.get("type") == "text"
        )
    else:
        result = response.content

    # If gemini wants to use the tool, run it and get final answer
    if response.tool_calls:
        tool_result = retriever_tool.invoke(response.tool_calls[0]["args"])
        result = f"{tool_result}"

    # Save to memory
    memory.add_message(HumanMessage(content=user_input))
    memory.add_message(AIMessage(content=result))

    return result


print("Turn 1: ")
response1 = chat("The company's Q1 revenue was $10M.")
print(f"FinAgent: {response1}\n")
print("=="*30)

print("Turn 2: ")
response2 = chat("What was the Q1 revenue?")
print(f"FinAgent: {response2}\n")
print("=="*30)

print("Chat Memory After Turn2: ")
for msg in memory.messages:
    role = "User" if isinstance(msg, HumanMessage) else "FinAgent"
    print(f"{role}: {msg.content}")
    

print("=="*30)

print("Turn 3: ")
response3 = chat("What is the definition of EBITDA?")
print(f"FinAgent: {response3}\n")
print("=="*30)
